server:
  port: 8081

spring:
  datasource:
    username: user_bgrktest
    password: user_bgrktest123
    url: jdbc:mysql://172.28.3.128:3306/yybgrk?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver



mybatis:
  type-aliases-package: com.example.selenium.model
  mapper-locations: classpath:mapper/*.xml


